# Generated by Django 5.2 on 2025-05-13 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisiofacil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='duracao',
            field=models.DurationField(default='01:00'),
            preserve_default=False,
        ),
    ]
