# Generated by Django 5.1.7 on 2025-03-22 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisiofacil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
