# Generated by Django 5.1.7 on 2025-03-22 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisiofacil', '0002_servico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='valor',
        ),
        migrations.AddField(
            model_name='servico',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ProfissionalServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('taxa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fisiofacil.profissional')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fisiofacil.servico')),
            ],
        ),
    ]
