# Generated by Django 5.1.7 on 2025-03-22 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisiofacil', '0003_remove_servico_valor_servico_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissionalservico',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
