# Generated by Django 5.2 on 2025-05-17 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisiofacil', '0004_rename_data_pagamento_pagamento_data_criacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='agendamento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pagamento', to='fisiofacil.agendamento'),
        ),
    ]
