# Generated by Django 5.1.7 on 2025-03-22 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisiofacil', '0004_profissionalservico_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='status',
        ),
        migrations.AddField(
            model_name='servico',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_inicio', models.DateTimeField()),
                ('data_hora_fim', models.DateTimeField()),
                ('cliente_nome', models.CharField(max_length=100)),
                ('cliente_email', models.EmailField(max_length=254)),
                ('cliente_telefone', models.CharField(max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('profissional_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fisiofacil.profissionalservico')),
            ],
        ),
    ]
