# Generated by Django 5.1.7 on 2025-03-22 04:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisiofacil', '0005_remove_servico_status_servico_valor_agendamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='data_hora_fim',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='data_hora_inicio',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='data',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='hora',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
