# Generated by Django 5.2 on 2025-05-17 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fisiofacil', '0005_alter_pagamento_agendamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profissionalservico',
            name='data_fim',
        ),
        migrations.RemoveField(
            model_name='profissionalservico',
            name='data_inicio',
        ),
        migrations.RemoveField(
            model_name='profissionalservico',
            name='taxa',
        ),
    ]
