# Generated by Django 5.2 on 2025-05-18 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisiofacil', '0006_remove_profissionalservico_data_fim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
